FROM ubuntu
MAINTAINER Daniel Utech <docker@utechnics.net>
RUN apt-get update && apt-get install -y \
    htop \
    nano \
    python-numpy \
    python-scipy \
    python-sympy \
    python-matplotlib \
    python-qrcode
